app/pages/models.py
from datetime import datetime
from slugify import slugify
from app import db


class Page(db.Model):
    __tablename__ = 'pages_pages'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    slug = db.Column(db.String(128))
    content = db.Column(db.String)
    created = db.Column(db.DateTime, default=datetime.utcnow)
    created = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.now)

    def __init__(self, *args, **kwargs):
        super(Page, self).__init__(*args, **kwargs)
        self.generate_slug()

    def __str__(self):
        return '%s : %s' % (self.id, self.title)

    def __repr__(self):
        return '<Page %r %r>' % (self.id, self.title)

    def generate_slug(self):
        self.slug = ''
        if self.title:
            self.slug = slugify(self.title)

app/pages/models/__init__.py
from app.pages.models.category import Category
from app.pages.models.post_tag import PostTag
from app.pages.models.tag import Tag
from app.pages.models.post import Post

app/pages/models/category.py
from app import db


class Category(db.Model):
    __tablename__ = 'pages_categories'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    posts = db.relationship('Post', backref="pages_categories")

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'<{__class__.__name__} "{self.name}">'

app/pages/models/post.py
from datetime import datetime
from slugify import slugify
from app.pages.models import PostTag
from app import db


class Post(db.Model):
    __tablename__ = 'pages_posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128))
    slug = db.Column(db.String(128))
    categories = db.Column(db.Integer, db.ForeignKey('pages_categories.id'))
    content = db.Column(db.String)
    created = db.Column(db.DateTime, default=datetime.utcnow)
    updated = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.now)
    online = db.Column(db.Boolean)
    tags = db.relationship('Tag', secondary=PostTag, backref='pages_posts')


    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def __str__(self):
        return '%s : %s' % (self.id, self.title)

    def __repr__(self):
        return '<Page %r %r>' % (self.id, self.title)

    def generate_slug(self):
        self.slug = ''
        if self.title:
            self.slug = slugify(self.title)

app/pages/models/post_tag.py
from app import db

PostTag = db.Table(
    'pages_post_tag',
    db.Column('posts_id', db.Integer, db.ForeignKey('pages_posts.id')),
    db.Column('tags_id', db.Integer, db.ForeignKey('pages_tags.id'))
)

app/pages/models/tag.py
from app import db


class Tag(db.Model):
    __tablename__ = 'pages_tags'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))

    def __str__(self):
        return self.name

    def __repr__(self):
        return f'<Tag "{self.name}">'

app/pages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, ValidationError, SelectField
from wtforms.validators import InputRequired


class PageForm(FlaskForm):
    title = StringField('titre', validators=[InputRequired(message="ne doit pas être vide")])
    category = SelectField('catégorie', choices=(('', 'choisir une catégorie'), (1, 'blog'), (2, 'static')), validators=[InputRequired(message="ne doit pas être vide")])
    content = TextAreaField('contenu', validators=[InputRequired(message="ne doit pas être vide")])
    online = BooleanField('en ligne', default='1')

    # def validate(self):
    #     count = 0
    #     if 'pizza' in self.title.data:
    #         self.title.errors += (ValidationError("pas de pizza"),)
    #         count += 1
    #
    #     return count == 0

app/__init__.py
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from app.config import config, basedir


db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # db
    db.init_app(app)
    migrate = Migrate()

    from app.pages.models import Post, PostTag, Tag, Category
    migrate.init_app(app, db, directory=basedir/'app'/'migrations')

    #admin
    admin = Admin(app, name='book administation')
    admin.add_view(ModelView(Post, db.session))
    admin.add_view(ModelView(Tag, db.session))
    admin.add_view(ModelView(Category, db.session))

    # views
    from app.main.errors import page_not_found, internal_server_error
    app.register_error_handler(404, page_not_found)
    app.register_error_handler(500, internal_server_error)

    from app.pages import bp as pages_views
    app.register_blueprint(pages_views)

    return app

app/pages/__init__.py
from flask import Blueprint


bp = Blueprint('pages', __name__)
from app.pages import views

app/pages/views.py
from pprint import pprint
from flask import render_template, request, flash, redirect, url_for
from app.pages import bp
from app.pages.models import Post
from app.pages.forms import PageForm
from app import db


@bp.route('/')
def index():
    ctx = {
        'books': 4,
        'authors': 5,
        'categories': 8,
    }
    return render_template('pages/index.html', **ctx)


@bp.route('/ajouter-page', methods=['GET', 'POST'])
def add():
    form = PageForm(request.form)
    if request.method == 'POST' and form.validate():
        data = {
            'title': form.title.data,
            'content': form.content.data,
            'online': 1 if form.online.data == True else 0,
        }
        new_post = Post(**data)
        db.session.add(new_post)
        db.session.commit()
        flash("creation page effectuée", "success")
        return redirect(url_for('pages.index'))
    ctx = {
        'form': form
    }
    return render_template('pages/add.html', **ctx)

app/templates/commons/field.html
{% if field.name != 'csrf_token' %}
    <div class="input {% if field.flags.required %}require{% endif %}">
        <span>{{ field.label }}</span>
        <span>{{ field }}</span>
        {% for error in field.errors %}
            <span class="error">{{ error }}</span>
        {% endfor %}
    </div>
{% endif %}

app/templates/commons/form.html
<form method="post">
    {{ form.csrf_token }}
    {% for field in form %}
        {% with field=field %}
            {% include 'commons/field.html' %}
        {% endwith %}
    {% endfor %}
    <button class="primary" type="submit">envoyer</button>
</form>

app/templates/commons/nav.html
<nav>
    <ul>
        <li><a href="/">front nav</a></li>
    </ul>
    <hr>
    <ul>
        <li><a href="{{ url_for('pages.add') }}">ajouter page</a></li>
    </ul>
</nav>

app/templates/default.html
<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/min.css') }}">
    </head>
    <body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="{{ category }}">
                    <p class="container">{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
        <main class="grid has-gutter-xl">
            <aside class="col-4">
                {% include 'commons/nav.html' %}
            </aside>
            <section class="col-8">
                <img src="{{ url_for('static', filename="img/logo.svg") }}" alt="" style="width: 50%; margin: 5rem auto 2.5rem; display: block;">
                {% block content %}{% endblock %}
            </section>
        </main>

        <script src="{{ url_for('static', filename='js/app.js') }}"></script>
    </body>
</html>

app/templates/pages/add.html
{% extends 'default.html' %}

{% block title %}ajouter une page{% endblock %}
{% block content %}
{% include 'commons/form.html' %}
{% endblock %}

app/templates/pages/index.html
{% extends 'default.html' %}

{% block title %}
index du catalogue
{% endblock %}


{% block content %}
<p>Une application basique avec <a href="https://flask.palletsprojects.com/" target="_blank">Flask</a> La bibliothèque contient au total : </p>
<ul>
    <li><strong>livres</strong> : {{ books }}</li>
    <li><strong>auteurs</strong> : {{ authors }}</li>
    <li><strong>categorie</strong> : {{ categories }}</li>
</ul>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Suscipit adipiscing bibendum est ultricies integer quis auctor. Senectus et netus et malesuada fames ac. Viverra justo nec ultrices dui sapien eget mi. Interdum varius sit amet mattis vulputate enim. Scelerisque purus semper eget duis at tellus at. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Adipiscing tristique risus nec feugiat in fermentum. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Mauris vitae ultricies leo integer malesuada nunc vel risus. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Et netus et malesuada fames ac turpis. Ullamcorper eget nulla facilisi etiam. Maecenas pharetra convallis posuere morbi leo. Gravida arcu ac tortor dignissim. Ante in nibh mauris cursus.
</p><p>
Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Donec enim diam vulputate ut pharetra. Nisl nisi scelerisque eu ultrices. Vel eros donec ac odio tempor orci. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Quisque sagittis purus sit amet volutpat consequat mauris. Neque sodales ut etiam sit amet nisl purus in. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Eu lobortis elementum nibh tellus molestie nunc non. Sapien nec sagittis aliquam malesuada. A condimentum vitae sapien pellentesque. Porttitor leo a diam sollicitudin tempor id.
</p><p>
Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Cursus eget nunc scelerisque viverra mauris in aliquam sem fringilla. In arcu cursus euismod quis viverra nibh. Ornare lectus sit amet est placerat in egestas erat. Viverra tellus in hac habitasse platea dictumst. Ut placerat orci nulla pellentesque dignissim enim sit. Ut lectus arcu bibendum at varius vel. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Tellus mauris a diam maecenas.
</p><p>
Non nisi est sit amet facilisis magna etiam tempor orci. Proin gravida hendrerit lectus a. Volutpat lacus laoreet non curabitur gravida. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Feugiat in fermentum posuere urna nec tincidunt praesent semper. Suspendisse interdum consectetur libero id. Elementum tempus egestas sed sed risus pretium quam. Enim sit amet venenatis urna cursus eget nunc scelerisque. Sed faucibus turpis in eu mi bibendum neque. Eu sem integer vitae justo eget magna fermentum. Lacus laoreet non curabitur gravida. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Quisque sagittis purus sit amet volutpat consequat mauris nunc. Facilisis leo vel fringilla est ullamcorper eget nulla.
</p><p>
Etiam non quam lacus suspendisse faucibus. Fermentum leo vel orci porta. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Egestas fringilla phasellus faucibus scelerisque. Tellus in metus vulputate eu scelerisque felis imperdiet proin fermentum. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. In arcu cursus euismod quis viverra. Mi bibendum neque egestas congue. Sed odio morbi quis commodo odio aenean sed adipiscing. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis.</p>
{% endblock %}